### ISSUE TITLE
Consider using `usize::MAX` as a default value for `plotting_range` variable

### ISSUE THREAD

**Issue by lonesometraveler** [hacknus/serial-monitor-rust#70]
Based on my understanding, `MyApp`'s `plotting_range` is used to limit the number of `PlotPoint` displayed on the screen. However, the default value of `-1_isize` is not very intuitive since it doesn't clearly indicate what it does. From the code, it appears that `-1` means to display all the `PlotPoints`. Would not it be better to use `usize::MAX` as the default value?

**Comment by hacknus** [comment]
from the coding side this sounds much more elegant than -1. how would you integrate it in the GUI? keep the -1 or add a special button? or maybe an exponential slider, that just goes to infinity (`usize::MAX`) on the far right side?

**Comment by lonesometraveler** [comment]
`usize::MAX` = `18446744073709551615`. So, you will see `18446744073709551615` in the GUI. 

If `plotting_range` is a `usize`, we can calculate the `window` variable like this.

```rust
let window = self.data.dataset[0]
                        .len()
                        .saturating_sub(self.plotting_range);
```
I find it easier to understand than the current implementation with `-1`.

While using `usize::MAX` as the default value for `plotting_range` would be more explicit, this could potentially result in performance issues, as it would cause the loop to iterate over the entire dataset. Also, the value `18446744073709551615` may not be desirable for users. Maybe we should set the default value to a more manageable value (100? 200? 1,000?) to make the code more user-friendly and avoid performance issues?

**Comment by hacknus** [comment]
I don't think performance is an issue. in the cases where you want to see the whole dataset we loop over the entire dataset, but this is ok in my opinion - it is the case now.

I agree that `usize::MAX` is more explicit, but I am unsure about the GUI implementation. there should certainly be a way to select "full dataset" as "-1" is now. I don't think typing in a large number or so is an elegant solution. I also think that "full dataset" should be the default. 

I think `egui::DragValue` has a `custom formatter` that we could use to display for example the infinity symbol instead of `usize::MAX` and maybe we add a button next to it to select an infinite window / full dataset?

**Comment by lonesometraveler** [comment]
I like #71. I left a couple of comments there.

**Comment by hacknus** [comment]
Perfect, thanks!
